### ISSUE TITLE
Support Grails 3

### ISSUE THREAD

**Issue by zyro23** [Grails-Plugin-Consortium/grails-cxf-client#53]
given Grails-3.0.0 just reached M2 and a final is planned to be released soon, it would be nice to see this plugin work with Grails 3 :)

(similar issue for grails-cxf here: https://github.com/Grails-Plugin-Consortium/grails-cxf/issues/45)

thanks, zyro

**Comment by ctoestreich** [comment]
Will be working on it soon along with a cxf upgrade.  Working on redis plugin now.

**Comment by longwa** [comment]
Any updates on the Grails 3 migration? We are looking to update and depend on this plugin. Thanks.
