### ISSUE TITLE
wss4j version conflict with cxf 3

### ISSUE THREAD

**Issue by bilgehanm** [Grails-Plugin-Consortium/grails-cxf-client#54]
With the new version of the plugin (2.1) i get an error during service calls. I think it is because of wss4j version conflict. Cxf 3 uses wssj4 2.0 but the build.config for dxf-client plugin requires a dependency for wss4j 1.6.18

ERROR client.WebServiceClientFactoryImpl$WSClientInvocationHandler  - org.apache.xml.security.utils.I18n.init(Ljava/util/ResourceBundle;)V
ERROR errors.GrailsExceptionResolver  - NoSuchMethodError occurred when processing request: [GET] /WebServiceConsumer/XXXX
org.apache.xml.security.utils.I18n.init(Ljava/util/ResourceBundle;)

**Comment by ctoestreich** [comment]
Yeah I saw that.  Fixing it now.  Looks like cxf 3 needs wss4j 2+.

**Comment by ctoestreich** [comment]
Released 2.1.1

**Comment by raminassar87** [comment]
I tried to update the pom version for wss4j but I still have the same error. can you help please @ctoestreich
