### ISSUE TITLE
Can't Access Interceptor(s)

### ISSUE THREAD

**Issue by burbidge** [Grails-Plugin-Consortium/grails-cxf-client#56]
I need to get the value of one of my outInterceptors properties, an audit id.
I tried to access the interceptor through the cxf client by casting the service to JaxWsClientProxy but this failed even though this is the class the debugger in IntelliJ shows. I can navigate the IntelliJ debugger to see the info I need but I'm unable to access it programatically. 

Is this possible?

Suggestions?

**Comment by ctoestreich** [comment]
More specifically, what are you trying to do with the value?

**Comment by burbidge** [comment]
I figured out how to access the information I needed.
