### ISSUE TITLE
No wsdlToJava target

### ISSUE THREAD

**Issue by qvarnis** [Grails-Plugin-Consortium/grails-cxf-client#64]
No gradle target named wsdlToJava when trying to generate code from wsdl.
build.gradle extract:

classpath "org.grails.plugins:grails-cxf-client:3.0.0-SNAPSHOT"

compile 'org.grails.plugins:grails-cxf:3.0.9'
compile 'org.grails.plugins:grails-cxf-client:3.0.3'

Any help appriciated ...

**Comment by ctoestreich** [comment]
Why do you have classpath "org.grails.plugins:grails-cxf-client:3.0.0-SNAPSHOT"?

**Comment by ctoestreich** [comment]
Have you tried running both `gradle wsdlToJava` and `grails wsdlToJava`?  Sometimes that might make a difference.

**Comment by qvarnis** [comment]
I just ripped the "classpath ...." from your demo app "https://github.com/Grails-Plugin-Consortium/grails-cxf-client-demo", in the hope that it would fix this issue :).

Neither of your suggestion work ie (gradle wsdlToJava or grails wsdlToJava)
===
gradle wsdlTOJava

FAILURE: Build failed with an exception.

* What went wrong:
Task 'wsdlTOJava' not found in root project 'timeedittool2'.

* Try:
Run gradle tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
===

We are using java 1.8.0_65, grails 3.0.11, gradle 2.10.
Heres my build.gradle
===
buildscript {
    ext {
        grailsVersion = project.grailsVersion
    }
    repositories {
        mavenLocal()
        maven { url "https://repo.grails.org/grails/core" }
    }
    dependencies {
        classpath "org.grails:grails-gradle-plugin:$grailsVersion"
        classpath 'com.bertramlabs.plugins:asset-pipeline-gradle:2.5.0'
        classpath "org.grails.plugins:hibernate:4.3.10.5"
        classpath "org.grails.plugins:grails-cxf-client:3.0.0-SNAPSHOT"
    }
}

plugins {
    id "io.spring.dependency-management" version "0.5.4.RELEASE"
}

version "0.1"
group "timeedittool2"

apply plugin: "spring-boot"
apply plugin: "war"
apply plugin: "asset-pipeline"
apply plugin: 'eclipse'
apply plugin: 'idea'
apply plugin: "org.grails.grails-web"
apply plugin: "org.grails.grails-gsp"

ext {
    grailsVersion = project.grailsVersion
    gradleWrapperVersion = project.gradleWrapperVersion
}

assets {
    minifyJs = true
    minifyCss = true
}

repositories {
    mavenLocal()
    maven { url "https://repo.grails.org/grails/core" }
    maven { url "http://maven.it.su.se/it.su.se/maven2/" }
    maven { url "https://dl.bintray.com/ctoestreich/grails-plugins/" }
}

dependencyManagement {
    imports {
        mavenBom "org.grails:grails-bom:$grailsVersion"
    }
    applyMavenExclusions false
}

dependencies {
    compile "org.springframework.boot:spring-boot-starter-logging"
    compile "org.springframework.boot:spring-boot-starter-actuator"
    compile "org.springframework.boot:spring-boot-autoconfigure"
    compile "org.springframework.boot:spring-boot-starter-tomcat"
    compile "org.grails:grails-dependencies"
    compile "org.grails:grails-web-boot"

    compile "org.grails.plugins:hibernate"
    compile "org.grails.plugins:cache"
    compile "org.hibernate:hibernate-ehcache"
    compile "org.grails.plugins:scaffolding"

    compile 'org.apache.directory.api:api-all:1.0.0-M28'
    compile 'org.grails.plugins:quartz:2.0.5'
    compile 'org.grails.plugins:grails-cxf:3.0.9'
    compile 'org.grails.plugins:grails-cxf-client:3.0.3'
    compile "se.su.it.tomcat:tomcat-header-encoding-valve:2.2"
    compile 'mysql:mysql-connector-java:5.1.37'

    runtime "org.grails.plugins:asset-pipeline"

    testCompile "org.grails:grails-plugin-testing"
    testCompile "org.grails.plugins:geb"

    // Note: It is recommended to update to a more robust driver (Chrome, Firefox etc.)
    testRuntime 'org.seleniumhq.selenium:selenium-htmlunit-driver:2.44.0'

    console "org.grails:grails-console"
}

task wrapper(type: Wrapper) {
    gradleVersion = gradleWrapperVersion
}
===

**Comment by ctoestreich** [comment]
Looking at this now.

**Comment by ctoestreich** [comment]
This should fix it.  Use the following for cxf client:

```
buildscript {
    //other stuff
    repositories {
        mavenLocal()
        maven { url "https://repo.grails.org/grails/core" }
        maven { url "https://dl.bintray.com/ctoestreich/grails-plugins" } //Required until grails repo is fixed
    }
    dependencies {
        //other stuff
        classpath "org.grails.plugins:grails-cxf-client:3.0.3" //This line
    }
}

dependencies {
    //other stuff
    compile 'org.grails.plugins:grails-cxf-client:3.0.3' //This line
}
```

**Comment by qvarnis** [comment]
Thank you for the help. You have always been very helpful and i just want you to know that is appriciated.
Keep up the good work!

**Comment by ctoestreich** [comment]
:+1:
